name: test-execution-and-reporting

on:
  push:
    branches:
      - master
      - feature/*
  schedule:
    - cron: "0 9 * * Mon"
  workflow_dispatch:
    inputs:
      execution:
        description: "Seleciona la razón de ejecución del pipeline"
        required: true
        type: choice
        options:
          - Falla en API get
          - Falla en API post
          - Falla en API put
          - Falla en API delete
          - Beta
      enviroment:
        description: "Seleccione el ambiente"
        required: true
        type: choice
        options:
          - Desarrollo
          - Staging
          - Produccion
      version:
        description: "Si seleccionaste 'Beta', indica la versión"
        required: false



